const exampleQuery =
  "> Homoserine_dh-consensus\n" +
  "CCTATCATTT CGACGCTCAA GGAGTCGCTG ACAGGTGACC GTATTACTCG\n" +
  "AATCGAAGGG ATATTAAACG GCACCCTGAA TTACATTCTC ACTGAGATGG\n" +
  "AGGAAGAGGG GGCTTCATTC TCTGAGGCGC TGAAGGAGGC ACAGGAATTG\n" +
  "GGCTACGCGG AAGCGGATCC TACGGACGAT GTGGAAGGGC TAGATGCTGC\n" +
  "TAGAAAGCTG GCAATTCTAG CCAGATTGGC ATTTGGGTTA GAGGTCGAGT\n" +
  "TGGAGGACGT AGAGGTGGAA GGAATTGAAA AGCTGACTGC CGAAGATATT\n" +
  "GAAGAAGCGA AGGAAGAGGG TAAAGTTTTA AAACTAGTGG CAAGCGCCGT\n" +
  "CGAAGCCAGG GTCAAGCCTG AGCTGGTACC TAAGTCACAT CCATTAGCCT\n" +
  "CGGTAAAAGG CTCTGACAAC GCCGTGGCTG TAGAAACGGA ACGGGTAGGC\n" +
  "GAACTCGTAG TGCAGGGACC AGGGGCTGGC GCAGAGCCAA CCGCATCCGC\n" +
  "TGTACTCGCT GACCTTCTC\n" +
  "\n" +
  "> AA_kinase-consensus\n" +
  "AAACGTGTAG TTGTAAAGCT TGGGGGTAGT TCTCTGACAG ATAAGGAAGA\n" +
  "GGCATCACTC AGGCGTTTAG CTGAGCAGAT TGCAGCATTA AAAGAGAGTG\n" +
  "GCAATAAACT AGTGGTCGTG CATGGAGGCG GCAGCTTCAC TGATGGTCTG\n" +
  "CTGGCATTGA AAAGTGGCCT GAGCTCGGGC GAATTAGCTG CGGGGTTGAG\n" +
  "GAGCACGTTA GAAGAGGCCG GAGAAGTAGC GACGAGGGAC GCCCTAGCTA\n" +
  "GCTTAGGGGA ACGGCTTGTT GCAGCGCTGC TGGCGGCGGG TCTCCCTGCT\n" +
  "GTAGGACTCA GCGCCGCTGC GTTAGATGCG ACGGAGGCGG GCCGGGATGA\n" +
  "AGGCAGCGAC GGGAACGTCG AGTCCGTGGA CGCAGAAGCA ATTGAGGAGT\n" +
  "TGCTTGAGGC CGGGGTGGTC CCCGTCCTAA CAGGATTTAT CGGCTTAGAC\n" +
  "GAAGAAGGGG AACTGGGAAG GGGATCTTCT GACACCATCG CTGCGTTACT\n" +
  "CGCTGAAGCT TTAGGCGCGG ACAAACTCAT AATACTGACC GACGTAGACG\n" +
  "GCGTTTACGA TGCCGACCCT AAAAAGGTCC CAGACGCGAG GCTCTTGCCA\n" +
  "GAGATAAGTG TGGACGAGGC CGAGGAAAGC GCCTCCGAAT TAGCGACCGG\n" +
  "TGGGATGAAG GTCAAACATC CAGCGGCTCT TGCTGCAGCT AGACGGGGGG\n" +
  "GTATTCCGGT CGTGATAACG AAT\n" +
  "\n" +
  "> 23ISL-consensus\n" +
  "CAGGGTCTGG ATAACGCTAA TCGTTCGCTA GTTCGCGCTA CAAAAGCAGA\n" +
  "AAGTTCAGAT ATACGGAAAG AGGTGACTAA CGGCATCGCT AAAGGGCTGA\n" +
  "AGCTAGACAG TCTGGAAACA GCTGCAGAGT CGAAGAACTG CTCAAGCGCA\n" +
  "CAGAAAGGCG GATCGCTAGC TTGGGCAACC AACTCCCAAC CACAGCCTCT\n" +
  "CCGTGAAAGT AAGCTTGAGC CATTGGAAGA CTCCCCACGT AAGGCTTTAA\n" +
  "AAACACCTGT GTTGCAAAAG ACATCCAGTA CCATAACTTT ACAAGCAGTC\n" +
  "AAGGTTCAAC CTGAACCCCG CGCTCCCGTC TCCGGGGCGC TGTCCCCGAG\n" +
  "CGGGGAGGAA CGCAAGCGCC CAGCTGCGTC TGCTCCCGCT ACCTTACCGA\n" +
  "CACGACAGAG TGGTCTAGGT TCTCAGGAAG TCGTTTCGAA GGTGGCGACT\n" +
  "CGCAAAATTC CAATGGAGTC ACAACGCGAG TCGACT";

export default exampleQuery;
