# Generated by Django 3.2.5 on 2021-11-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deciphon_submission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submittedjob",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
